spring:
  main:
    banner-mode: off
  application:
    name: ong_adocao
  datasource:

    url: jdbc:mariadb://${MARIADB_HOST:localhost}:3307/ong_adocao?useSSL=false&serverTimezone=UTC


    username: root
    password: root


    driver-class-name: org.mariadb.jdbc.Driver

    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080