#spring:
#  main:
#    banner-mode: off
#  application:
#    name: ong_adocao
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ong_adocao?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#
#
#    spring:
#      datasource:
#        url=jdbc:mariadb://localhost:3306/ong_adocao?useSSL=false&serverTimezone=UTC:
#    username: root
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#
#server:
#  port: 8081



# Configurações do Spring Boot
spring:
  main:
    banner-mode: off
  application:
    name: ong_adocao

  # --- Configurações do Banco de Dados para MariaDB ---
  datasource:
    # 1. URL correta para o driver do MariaDB
    #TODO: Isa (no meu banco eu instalei a porta como 3308, por isso precisa alterar quando for rodar isso)
    url: jdbc:mariadb://localhost:3308/ong_adocao?useSSL=false&serverTimezone=UTC
    username: root
    password: root # Continua lendo a senha de uma variável de ambiente, o que é uma ótima prática!
    # 2. Driver correto para o MariaDB
    driver-class-name: org.mariadb.jdbc.Driver

  # --- Configurações do JPA/Hibernate ---
  jpa:
    hibernate:
      # Cria ou atualiza o schema do banco ao iniciar a aplicação
      ddl-auto: update
    show-sql: true # Mostra os comandos SQL no console
    properties:
      hibernate:
        # 3. Dialeto correto para o MariaDB
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true # Formata o SQL exibido no console para melhor leitura

  # --- Configurações do Spring MVC ---
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# --- Configurações do Servidor ---
server:
  port: 8081